CXXFLAGS = -std=c++17 -fopenmp

all: trab

trab: util.cpp Config.cpp Populacao.cpp Problem.hpp CodBinaria.cpp CodInteira.cpp CodPermutada.cpp CodReal.cpp gera_pop.cpp
	g++-7 $(CXXFLAGS) util.cpp Config.cpp Populacao.cpp Problem.hpp CodBinaria.cpp CodInteira.cpp CodPermutada.cpp CodReal.cpp gera_pop.cpp
